// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
.......ff...............
....ffff2ff.............
..ffeeeef2ff............
.ffeeeeef22ff...........
.feeeeffeeeef...........
.fffffee2222ef..........
fffe222ffffe2f..........
ffffffffeeefff..........
fefe44ebf44eef..........
.fee4d4bfddef...........
..feee4dddee.c..........
...f2222eeddeccccccc....
...f444e44ddecddddd.....
...fffffeeee.ccccc......
..ffffffff...c..........
..fff..ff...............
........................
........................
........................
........................
........................
........................
........................
........................
`;
            case "image2":
            case "myImage0":return img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..........ee............
.........ccc............
........cc1cc...........
.........c1c............
.........c1c............
.........c1c............
.........c1c............
`;
            case "image3":
            case "myImage1":return img`
...............ff.......
.............ff2ffff....
............ff2feeeeff..
...........ff22feeeeeff.
...........feeeeffeeeef.
..........fe2222eefffff.
..........f2effff222efff
..........fffeeeffffffff
..........fee44fbe44efef
...........feddfb4d4eef.
..........c.eeddd4eeef..
....ccccccceddee2222f...
.....dddddcedd44e444f...
......ccccc.eeeefffff...
..........c...ffffffff..
...............ff..fff..
........................
........................
........................
........................
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
